### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by sstangl** [meethed/simpleLifter#23]
Hey, I'm from OpenPowerlifting, and we're looking to see if we can help simpleLifter have more direct output to the OpenLifter format, so we can import APU meets more easily.

I noticed that this repository doesn't have a `LICENSE` file. Would it be possible to add one, so that this repo qualifies as open source?

OpenPowerlifting projects are all licensed under the AGPLv3. If that license sounds decent to you, our `LICENSE` file is located here: https://gitlab.com/openpowerlifting/opl-data/-/blob/main/LICENSE

**Comment by meethed** [comment]
Hey bro yeah of course.

I mean I could probably knock something up in a few minutes but I'll sort out GPL license for ya

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Sean Stangl ***@***.***>
Sent: Tuesday, May 9, 2023 6:57:48 PM
To: meethed/simpleLifter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [meethed/simpleLifter] Missing LICENSE file (Issue #23)


Hey, I'm from OpenPowerlifting, and we're looking to see if we can help simpleLifter have more direct output to the OpenLifter format, so we can import APU meets more easily.

I noticed that this repository doesn't have a LICENSE file. Would it be possible to add one, so that this repo qualifies as open source?

OpenPowerlifting projects are all licensed under the AGPLv3. If that license sounds decent to you, our LICENSE file is located here: https://gitlab.com/openpowerlifting/opl-data/-/blob/main/LICENSE

**Comment by meethed** [comment]
GPL v3 added :)
